name: Performance Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

jobs:
  # Load Testing
  load-test:
    name: Load Testing
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build application
        working-directory: ./server
        run: npm run build

      - name: Start application
        working-directory: ./server
        run: |
          npm start &
          sleep 10
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://localhost:27017/taxi_app_test
          JWT_SECRET: test-secret-key

      - name: Install Artillery
        run: npm install -g artillery@latest

      - name: Run load tests
        run: |
          cat > load-test.yml << EOF
          config:
            target: 'http://localhost:3001'
            phases:
              - duration: 60
                arrivalRate: 10
              - duration: 120
                arrivalRate: 20
              - duration: 60
                arrivalRate: 5
            defaults:
              headers:
                Content-Type: 'application/json'
          scenarios:
            - name: "Health Check"
              weight: 30
              flow:
                - get:
                    url: "/health"
            - name: "User Registration and Login"
              weight: 40
              flow:
                - post:
                    url: "/api/auth/register"
                    json:
                      name: "Test User {{ \$randomString() }}"
                      email: "test{{ \$randomString() }}@example.com"
                      phone: "+491234567890"
                      password: "password123"
                      role: "customer"
                - post:
                    url: "/api/auth/login"
                    json:
                      email: "test@example.com"
                      password: "password123"
            - name: "API Endpoints"
              weight: 30
              flow:
                - get:
                    url: "/api/auth/me"
                    headers:
                      Authorization: "Bearer fake-token"
          EOF
          
          artillery run load-test.yml --output report.json

      - name: Generate HTML report
        run: artillery report report.json

      - name: Upload performance report
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: report.json.html

  # Lighthouse Performance Audit (for API documentation page)
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:3001/health
          budgetPath: './server/.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true